# Generated by Django 3.0.5 on 2020-05-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mbti',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
