# Generated by Django 3.0.5 on 2020-05-23 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200519_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birthday',
            new_name='hobby',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='snsaddress',
            new_name='instaid',
        ),
    ]
