# Generated by Django 3.0.5 on 2020-05-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200519_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
