# Generated by Django 3.0.5 on 2020-05-30 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200523_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='instaid',
            new_name='insta_id',
        ),
    ]
