# Generated by Django 3.0.5 on 2020-05-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_sns'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
