# Generated by Django 3.0.5 on 2020-05-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200521_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sns',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
