# Generated by Django 3.0.6 on 2020-06-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedcomment',
            name='author',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
