# Generated by Django 3.0.5 on 2020-05-30 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0003_auto_20200530_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='title',
        ),
    ]
