# Generated by Django 3.0.6 on 2020-05-30 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='college',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='major',
        ),
    ]
