# Generated by Django 3.0.4 on 2020-05-30 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0004_feed_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='photo',
        ),
    ]
