# Generated by Django 3.0.4 on 2020-05-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0005_remove_feed_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='photo',
            field=models.ImageField(blank=True, upload_to='feed_photds'),
        ),
    ]
