# Generated by Django 3.0.1 on 2020-05-16 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
