# Generated by Django 3.0.6 on 2020-05-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0002_auto_20200525_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedcomment',
            options={'ordering': ['-like_count']},
        ),
        migrations.AddField(
            model_name='feedcomment',
            name='like_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
