# Generated by Django 3.0.5 on 2020-05-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0003_auto_20200523_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='photo',
            field=models.ImageField(blank=True, upload_to='feed_photos'),
        ),
    ]
