# Generated by Django 3.0.5 on 2020-05-23 07:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedpage', '0003_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_feeds', through='feedpage.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
