# Generated by Django 3.0.6 on 2020-05-23 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0003_auto_20200523_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='like_user',
            new_name='like_users',
        ),
    ]
