# Generated by Django 3.0.5 on 2020-05-29 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0005_auto_20200529_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedcomment',
            old_name='love_users',
            new_name='like_users',
        ),
    ]
