# Generated by Django 3.0.5 on 2020-05-30 02:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedpage', '0005_auto_20200526_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedcomment',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_feedcomments', through='feedpage.CommentLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
