# Generated by Django 3.1 on 2020-08-27 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='langauage',
            new_name='language',
        ),
    ]
